### ISSUE TITLE
Scrolling has to be more precise

### ISSUE THREAD

**Issue by andorfermichael** [crowdbotics-users/audvice-native-audio-recorder#25]
**Is your feature request related to a problem? Please describe.**
Scrolling is currently not precise enough. For example, you cannot scroll from 01:00:00 to 01:00:01.

**Describe the solution you'd like**
It should be possible to scroll in 1 ms steps.

**Comment by scbopha** [comment]
We cannot process the scroll in 1 ms step, because the waveform is drawing about 100 pixels per 1s.
So we can scroll only 1/100s, by 1 pixel.

**Comment by andorfermichael** [comment]
Okay, I see. I will close it as it is not possible with our current conditions of pixelsPerSecond.
