### ISSUE TITLE
Scrolling animation is jerking

### ISSUE THREAD

**Issue by andorfermichael** [crowdbotics-users/audvice-native-audio-recorder#27]
**Is your feature request related to a problem? Please describe.**
The scrolling animation during recording and playing is jerking.

**Describe the solution you'd like**
The scrolling animation should be smooth without any kind of jerking.

**Comment by scbopha** [comment]
Jerking is occurred by time interval to get audio data from input device.
In iOS, I modified the record time interval with 50ms, so scroll is updated by 1/20s, and play is updated by 1/50s(20ms)
And android, record is updated by 1/40s and play is update by 1/40s.
As I test it, it's just minimum values for record and play.

**Comment by andorfermichael** [comment]
Resolved
