### ISSUE TITLE
Recording not working after app was in background mode on iOS

### ISSUE THREAD

**Issue by andorfermichael** [crowdbotics-users/audvice-native-audio-recorder#29]
**Is your feature request related to a problem? Please describe.**
When an audio is recorded and the app goes into background mode and comes into foreground again, recording does not work. 

**Describe the solution you'd like**
Recording should work even if app was in background mode.

**Comment by ateqpm** [comment]
Hi @andorfermichael  @3rfan  we have completed this ticket and pushed the code in master branch and it is ready for your review. Please verify. thanks

**Comment by andorfermichael** [comment]
Resolved
